{% set name = "cubed" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cubed-{{ version }}.tar.gz
  sha256: 96d4d0b808c89445a991be2e2650cfd54d7bdd6c3927fe4bbfff5bdc77bfb209

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=42
    - setuptools_scm >=3.4
    - toml
  run:
    - cloudpickle
    - donfig
    - python >=3.9
    - aiostream
    - array-api-compat
    - fsspec
    - mypy_extensions
    - networkx <2.8.3
    - numpy >=1.22
    - tenacity
    - toolz
    - zarr

test:
  imports:
    - cubed
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tomwhite/cubed
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Bounded-memory serverless distributed N-dimensional array processing
  doc_url: tomwhite.github.io/cubed
  dev_url: https://github.com/tomwhite/cubed

extra:
  recipe-maintainers:
    - TomNicholas
    - tomwhite
