{% set name = "cubed" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cubed-{{ version }}.tar.gz
  sha256: de88b46972629cbbdd1200e264789613139187cdb5b46aead13e8c9e43acbc02

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=42
    - setuptools_scm >=3.4
    - toml
  run:
    - cloudpickle
    - donfig
    - python >=3.9
    - aiostream
    - array-api-compat
    - fsspec
    - mypy_extensions
    - networkx !=2.8.3,!=2.8.4,!=2.8.5,!=2.8.6,!=2.8.7,!=2.8.8,!=3.0.*,!=3.1.*,!=3.2.*
    - numpy >=1.22
    - tenacity
    - toolz
    - zarr

test:
  imports:
    - cubed
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cubed-dev/cubed
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Bounded-memory serverless distributed N-dimensional array processing
  doc_url: https://cubed-dev.github.io/cubed/
  dev_url: https://github.com/cubed-dev/cubed

extra:
  recipe-maintainers:
    - TomNicholas
    - tomwhite
