{% set name = "cubed" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7356947ec2cb2d211b5db9484e27fc736118ec650ab6291df89e65dcdcf41f53

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=42
    - setuptools_scm >=3.4
    - toml
  run:
    - aiostream
    - fsspec
    - mypy_extensions # for rechunker
    - networkx <2.8.3
    - numpy >=1.22
    - tenacity
    - toolz
    - zarr
    - python >=3.8

test:
  imports:
    - cubed
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tomwhite/cubed
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Bounded-memory serverless distributed N-dimensional array processing
  doc_url: tomwhite.github.io/cubed
  dev_url: https://github.com/tomwhite/cubed

extra:
  recipe-maintainers:
    - TomNicholas
    - tomwhite
