{% set name = "cubed" %}
{% set version = "0.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cubed-{{ version }}.tar.gz
  sha256: 4460665b4b60b29b71bfa138cff8f5a597aded90341d5c751274c1914d1ef28d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools >=42
    - setuptools_scm >=3.4
    - toml
  run:
    - ndindex
    - psutil
    - cloudpickle
    - donfig
    - python >=3.11
    - aiostream
    - array-api-compat
    - fsspec
    - mypy_extensions
    - networkx >=3.3
    - numpy >=2
    - tenacity
    - toolz
    - zarr >3.1.2

test:
  imports:
    - cubed
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cubed-dev/cubed
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Scalable array processing with bounded memory
  doc_url: https://cubed-dev.github.io/cubed/
  dev_url: https://github.com/cubed-dev/cubed

extra:
  recipe-maintainers:
    - TomNicholas
    - tomwhite
